# Generated by Django 5.0.3 on 2024-04-04 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 19, 59, 46, 740175)),
        ),
    ]
