# Generated by Django 5.0.3 on 2024-04-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_signup_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='datetime',
        ),
        migrations.AddField(
            model_name='signup',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 16, 56, 7, 438856)),
        ),
    ]
