# Generated by Django 5.0.3 on 2024-04-10 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_signup_datetime_signup_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
